name: CD - Deploy to Cloud

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Build Docker image and Push to AWS ECR and Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup job
        uses: ./.github/actions/log-streamer
        with:
          step_name: "Setup job"
          command: |
            echo "Runner environment: $(uname -a)"
            echo "Available disk space: $(df -h / | tail -1)"
            echo "Memory info: $(free -h)"
            echo "Job setup completed"
          endpoint: https://app.mayson.dev/api/v1/logs/github
          token: none

      - name: Checkout code
        uses: ./.github/actions/log-streamer
        with:
          step_name: "Checkout code"
          command: |
            echo "Code checkout completed"
            echo "Repository: ${{ github.repository }}"
            echo "Branch: ${{ github.ref_name }}"
            echo "Commit SHA: ${{ github.sha }}"
            ls -la
          endpoint: https://app.mayson.dev/api/v1/logs/github
          token: none

      - name: Install Kube Control
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.31.0'
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        uses: ./.github/actions/log-streamer
        with:
          step_name: "Build, tag, and push docker image to Amazon ECR"
          command: |
            docker build -t ${{ steps.login-ecr.outputs.registry }}/backstract_apps:${{ github.sha }} -t ${{ steps.login-ecr.outputs.registry }}/backstract_apps:coll-ac2c068b8e674f04ac93f077b0e1f594 .
            docker push -a ${{ steps.login-ecr.outputs.registry }}/backstract_apps
          endpoint: https://app.mayson.dev/api/v1/logs/github
          token: none

      - name: Update kube config to point to EKS
        uses: ./.github/actions/log-streamer
        with:
          step_name: "Update kube config to point to EKS"
          command: aws eks update-kubeconfig --name backstract-dev --region ap-south-1
          endpoint: https://app.mayson.dev/api/v1/logs/github
          token: none

      - name: Deploy to AWS EKS Cluster
        uses: ./.github/actions/log-streamer
        with:
          step_name: "Deploy to AWS EKS Cluster"
          command: |
            kubectl apply -f infra/k8s/alloy-rbac.yaml
            kubectl apply -f infra/k8s/alloy-configmap.yaml
            kubectl apply -f infra/k8s/aws-auth.yaml
            kubectl apply -f infra/k8s/deployment.yaml
            kubectl apply -f infra/k8s/service.yaml
            kubectl rollout restart deployment coll-ac2c068b8e674f04ac93f077b0e1f594-depl
            kubectl apply -f infra/k8s/aws-auth.yaml
          endpoint: https://app.mayson.dev/api/v1/logs/github
          token: none